### ISSUE TITLE
No requerido en post

### ISSUE THREAD

**Issue by ruchus** [DavidMarquezF/osTicket-google-recaptcha#3]
A pesar de configurar el campo de formulario como requerido es posible enviarlo sin marcar la casilla del captcha.

Para reproducirlo:

-Abrir el formulario de nuevo ticket /open.php
-Cumplimentar todos los campos de formulario, sin marcar el captcha.
-Enviar el formulario.

**Comment by DavidMarquezF** [comment]
A mí me funciona correctamente. ¿Le has añadido el nombre de variable?
Este nombre es arbitrario, no tiene importáncia (en mi caso, gRecaptcha)

**Comment by DavidMarquezF** [comment]
I'll close this issue because I cannot reproduce it. If this still happens with the latest version, feel free to reopen it
