### ISSUE TITLE
Compatibility with 1.16

### ISSUE THREAD

**Issue by coder66** [DavidMarquezF/osTicket-google-recaptcha#5]
This plugin does not seem to work with 1.16 anymore. Will it be updated, or can someone point to how to get it working with 1.16?

**Comment by DavidMarquezF** [comment]
I haven't tested it with 1.16 yet. I am not sure if I'm going to have time soon to do this, so unless you want go for it yourself the other solution is to stick with the latest version it works

**Comment by coder66** [comment]
Any update on this topic? Anyone with an idea what needs to be fixed to get this working again?

**Comment by DavidMarquezF** [comment]
No I haven't had a look yet and I am not sure if I'm going to have anytime soon. I have too much work right now and so I can't put in more time to investigate and fix this issue unfortunately. Any contribution is appretiated though :)

I'm currently using ostickets 1.15.3.1  I believe and eveything works. 

If you want to try to fix it I think that in 1.16 they updated the php to version 8 which may have introduced some breaking changes? Or maybe they changed some parts of how plugins work internally.

**Comment by DavidMarquezF** [comment]
I made the necessary changes to make it work with osTickets 1.17. You can get it in the latest release

**Comment by coder66** [comment]
Wow - thank you 😀
